version: '3.8'
services:
  db:
    image: postgres:15
    container_name: erp_sales_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sales_db
    ports:
      - "5432:5432"  # Kita pakai port standar lagi
    volumes:
      - postgres_data_final:/var/lib/postgresql/data # Nama volume baru agar fresh

volumes:
  postgres_data_final: